name: Build app
on: push

jobs:
  build_on_win:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'skip-publish')"

    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            flutter_path: /opt/hostedtoolcache/flutter

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-install-cache-${{ env.flutter_version }}
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
